engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    config:
      config: /usr/src/app/.eslintrc
  fixme:
    enabled: true
ratings:
   paths:
   - "**.js"
exclude_paths:
  - config/
  - test/
