#%RAML 0.8
title: rest-agenda
version: 0.1.0
mediaType: application/json
baseUri: /
documentation:
 - title: Getting Started
   content: !include ../README.md
resourceTypes:
  - callback:
      description: Entity representing a read-only <<resourcePathName|!singularize>>
      post:
        description: |
          Test the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}
          If called anonymously, the <<resourcePathName|!singularize>>
          must be public.
        body:
          application/json:
            schema: |
              <<schemaItem>>
              #<<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleItem>>
                schema: <<schemaItem>>
  - collection:
      is: [versionable]
      securedBy: [null]
      description: Collection of available <<resourcePathName>> in REST-Scheduler.
      get:
        description: |
          Get a list of <<resourcePathName>>.  If called anonymously,
          this will return all public <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
                schema: <<schemaCollection>>
      post:
        description: |
          Add a new <<resourcePathName|!singularize>> to REST-Scheduler.
        queryParameters:
          access_token:
            description: "The access token provided by the authentication application"
            example: AABBCCDD
            required: true
            type: string
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          200:
            body:
              application/json:
                example:
  - create-job:
      description: Create an entity representing a <<resourcePathName|!singularize>>
      post:
        description: |
          Add a new <<resourcePathName|!singularize>> to REST-Scheduler.
        headers:
          Content-Type:
            description: the required content type and encoding
            type: string
            example: |
              application/json; charset=utf-8
        body:
          application/json:
            schema: |
              <<schemaItem>>
              #<<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          200:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: <<exampleItem>>
                schema: <<schemaItem>>
          400:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: |
                  {"message": "We could not process your request <<resourcePathName|!singularize>>" }
          500:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: |
                  {"message": "Job <<resourcePathName|!singularize>> could not be created" }
  - job:
      description: Entity representing a <<resourcePathName|!singularize>>
      get:
        description: |
          Get the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}
        headers:
          Content-Type:
            description: the required content type and encoding
            type: string
            example: |
              application/json; charset=utf-8
        responses:
          200:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: <<exampleItem>>
                schema: <<schemaItem>>
          400:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: |
                  {"message": "<<resourcePathName|!singularize>> not found" }
      put:
        description: |
          Update the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}.
        headers:
          Content-Type:
            description: the required content type and encoding
            type: string
            example: |
              application/json; charset=utf-8
        body:
          application/json:
            schema: <<schemaItem>>
            example: <<exampleItem>>
        responses:
          200:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: <<exampleItem>>
                schema: <<schemaItem>>
          400:
            headers:
              Content-Type:
                description: the required content type and encoding
                type: string
                example: |
                  application/json; charset=utf-8
            body:
              application/json:
                example: |
                  {"message": "Job <<resourcePathName|!singularize>> not found" }

traits:
- versionable:
      headers:
        Accept-Version:
          description: the version that is acceptable according to semver.org matching
          type: string
          example: ~1
      responses:
        200:
          headers:
            Version:
              description: the (semver) version provided
              type: string
              example: 1.0.6


/:
  displayName: Create Job
  type:
    create-job:
      exampleItem: |
        {
          "meta": {
            "time": "2016-03-18T06:54:25.567Z",
            "request": {
              "name": "1 job",
              "data": {
                "when": "in 1 second",
                "url": "http://localhost:3000/testcburl",
                "name": "1 job"
              },
              "type": "normal",
              "priority": 0,
              "nextRunAt": "2016-03-18T06:54:26.568Z",
              "_id": "56eba62139a48fc980b3495d"
            }
          }
        }
      schemaItem: |
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "id": "/",
          "type": "object",
          "properties": {
            "meta": {
              "id": "meta",
              "type": "object",
              "properties": {
                "time": {
                  "id": "time",
                  "type": "string"
                },
                "request": {
                  "id": "request",
                  "type": "object",
                  "properties": {
                    "name": "[object Object]",
                    "data": {
                      "id": "data",
                      "type": "object",
                      "properties": {
                        "when": {
                          "id": "when",
                          "type": "string"
                        },
                        "url": {
                          "id": "url",
                          "type": "string"
                        },
                        "name": "[object Object]"
                      },
                      "additionalProperties": true
                    },
                    "type": {
                      "id": "type",
                      "type": "string"
                    },
                    "priority": {
                      "id": "priority",
                      "type": "integer"
                    },
                    "nextRunAt": {
                      "id": "nextRunAt",
                      "type": "string"
                    },
                    "_id": {
                      "id": "_id",
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "additionalProperties": false,
              "required": [
                "time",
                "request"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "meta"
          ]
        }
  description: this is the action that will fire at some time in the future
  post:
    protocols:
      - HTTP
      - HTTPS
    body:
      application/json:
        example: !include ./examples/actionReqObj.json
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "id": "/",
            "type": "object",
            "properties": {
              "when": {
                "id": "when",
                "type": "string"
              },
              "url": {
                "id": "url",
                "type": "string"
              },
              "name": {
                "id": "name",
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "when",
              "url",
              "name"
            ]
          }
    responses:
      200:
        body:
          application/json:
            #example:  |
              {
                "meta": {
                  "time": "2016-03-18T06:54:25.567Z",
                  "request": {
                    "name": "1 job",
                    "data": {
                      "when": "in 1 second",
                      "url": "http://localhost:3000/testcburl",
                      "name": "1 job"
                    },
                    "type": "normal",
                    "priority": 0,
                    "nextRunAt": "2016-03-18T06:54:26.568Z",
                    "_id": "56eba62139a48fc980b3495d"
                  }
                }
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "/",
                "type": "object",
                "properties": {
                  "meta": {
                    "id": "meta",
                    "type": "object",
                    "properties": {
                      "time": {
                        "id": "time",
                        "type": "string"
                      },
                      "request": {
                        "id": "request",
                        "type": "object",
                        "properties": {
                          "name": "[object Object]",
                          "data": {
                            "id": "data",
                            "type": "object",
                            "properties": {
                              "when": {
                                "id": "when",
                                "type": "string"
                              },
                              "url": {
                                "id": "url",
                                "type": "string"
                              },
                              "name": "[object Object]"
                            },
                            "additionalProperties": true
                          },
                          "type": {
                            "id": "type",
                            "type": "string"
                          },
                          "priority": {
                            "id": "priority",
                            "type": "integer"
                          },
                          "nextRunAt": {
                            "id": "nextRunAt",
                            "type": "string"
                          },
                          "_id": {
                            "id": "_id",
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false,
                    "required": [
                      "time",
                      "request"
                    ]
                  }
                },
                "additionalProperties": false,
                "required": [
                  "meta"
                ]
              }
/{jobid}:
  type:
    job:
      exampleItem: |
        {
          "meta": {
            "time": "2016-03-18T06:54:25.567Z",
            "request": {
              "name": "1 job",
              "data": {
                "when": "in 1 second",
                "url": "http://localhost:3000/testcburl",
                "name": "1 job"
              },
              "type": "normal",
              "priority": 0,
              "nextRunAt": "2016-03-18T06:54:26.568Z",
              "_id": "56eba62139a48fc980b3495d"
            }
          }
        }
      schemaItem: |
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "id": "/",
          "type": "object",
          "properties": {
            "meta": {
              "id": "meta",
              "type": "object",
              "properties": {
                "time": {
                  "id": "time",
                  "type": "string"
                },
                "request": {
                  "id": "request",
                  "type": "object",
                  "properties": {
                    "name": "[object Object]",
                    "data": {
                      "id": "data",
                      "type": "object",
                      "properties": {
                        "when": {
                          "id": "when",
                          "type": "string"
                        },
                        "url": {
                          "id": "url",
                          "type": "string"
                        },
                        "name": "[object Object]"
                      },
                      "additionalProperties": true
                    },
                    "type": {
                      "id": "type",
                      "type": "string"
                    },
                    "priority": {
                      "id": "priority",
                      "type": "integer"
                    },
                    "nextRunAt": {
                      "id": "nextRunAt",
                      "type": "string"
                    },
                    "_id": {
                      "id": "_id",
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "additionalProperties": false,
              "required": [
                "time",
                "request"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "meta"
          ]
        }
  description: this is the action that will fire at some time in the future
  displayName: Job
  get:
    displayName: Get Job
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "meta": {
                  "time": "2016-03-18T06:54:25.567Z",
                  "request": {
                    "name": "1 job",
                    "data": {
                      "when": "in 1 second",
                      "url": "http://localhost:3000/testcburl",
                      "name": "1 job"
                    },
                    "type": "normal",
                    "priority": 0,
                    "nextRunAt": "2016-03-18T06:54:26.568Z",
                    "_id": "56eba62139a48fc980b3495d"
                  }
                }
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "/",
                "type": "object",
                "properties": {
                  "meta": {
                    "id": "meta",
                    "type": "object",
                    "properties": {
                      "time": {
                        "id": "time",
                        "type": "string"
                      },
                      "request": {
                        "id": "request",
                        "type": "object",
                        "properties": {
                          "name": "[object Object]",
                          "data": {
                            "id": "data",
                            "type": "object",
                            "properties": {
                              "when": {
                                "id": "when",
                                "type": "string"
                              },
                              "url": {
                                "id": "url",
                                "type": "string"
                              },
                              "name": "[object Object]"
                            },
                            "additionalProperties": true
                          },
                          "type": {
                            "id": "type",
                            "type": "string"
                          },
                          "priority": {
                            "id": "priority",
                            "type": "integer"
                          },
                          "nextRunAt": {
                            "id": "nextRunAt",
                            "type": "string"
                          },
                          "_id": {
                            "id": "_id",
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false,
                    "required": [
                      "time",
                      "request"
                    ]
                  }
                },
                "additionalProperties": false,
                "required": [
                  "meta"
                ]
              }
  put:
    displayName: Update Job
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "meta": {
                  "time": "2016-03-18T06:54:25.567Z",
                  "request": {
                    "name": "1 job",
                    "data": {
                      "when": "in 1 second",
                      "url": "http://localhost:3000/testcburl",
                      "name": "1 job"
                    },
                    "type": "normal",
                    "priority": 0,
                    "nextRunAt": "2016-03-18T06:54:26.568Z",
                    "_id": "56eba62139a48fc980b3495d"
                  }
                }
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "/",
                "type": "object",
                "properties": {
                  "meta": {
                    "id": "meta",
                    "type": "object",
                    "properties": {
                      "time": {
                        "id": "time",
                        "type": "string"
                      },
                      "request": {
                        "id": "request",
                        "type": "object",
                        "properties": {
                          "name": "[object Object]",
                          "data": {
                            "id": "data",
                            "type": "object",
                            "properties": {
                              "when": {
                                "id": "when",
                                "type": "string"
                              },
                              "url": {
                                "id": "url",
                                "type": "string"
                              },
                              "name": "[object Object]"
                            },
                            "additionalProperties": true
                          },
                          "type": {
                            "id": "type",
                            "type": "string"
                          },
                          "priority": {
                            "id": "priority",
                            "type": "integer"
                          },
                          "nextRunAt": {
                            "id": "nextRunAt",
                            "type": "string"
                          },
                          "_id": {
                            "id": "_id",
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false,
                    "required": [
                      "time",
                      "request"
                    ]
                  }
                },
                "additionalProperties": false,
                "required": [
                  "meta"
                ]
              }
  delete:
    displayName: Delete Job
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "meta": {
                  "time": "2016-03-18T06:54:25.567Z",
                  "request": {
                    "name": "1 job",
                    "data": {
                      "when": "in 1 second",
                      "url": "http://localhost:3000/testcburl",
                      "name": "1 job"
                    },
                    "type": "normal",
                    "priority": 0,
                    "nextRunAt": "2016-03-18T06:54:26.568Z",
                    "_id": "56eba62139a48fc980b3495d"
                  }
                }
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "/",
                "type": "object",
                "properties": {
                  "meta": {
                    "id": "meta",
                    "type": "object",
                    "properties": {
                      "time": {
                        "id": "time",
                        "type": "string"
                      },
                      "request": {
                        "id": "request",
                        "type": "object",
                        "properties": {
                          "name": "[object Object]",
                          "data": {
                            "id": "data",
                            "type": "object",
                            "properties": {
                              "when": {
                                "id": "when",
                                "type": "string"
                              },
                              "url": {
                                "id": "url",
                                "type": "string"
                              },
                              "name": "[object Object]"
                            },
                            "additionalProperties": true
                          },
                          "type": {
                            "id": "type",
                            "type": "string"
                          },
                          "priority": {
                            "id": "priority",
                            "type": "integer"
                          },
                          "nextRunAt": {
                            "id": "nextRunAt",
                            "type": "string"
                          },
                          "_id": {
                            "id": "_id",
                            "type": "string"
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false,
                    "required": [
                      "time",
                      "request"
                    ]
                  }
                },
                "additionalProperties": false,
                "required": [
                  "meta"
                ]
              }

/testcburl:
  displayName: Callback URL for testing
  type:
    callback:
      schemaItem: |
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "id": "/",
          "type": "object",
          "properties": {
            "meta": {
              "id": "meta",
              "type": "object",
              "properties": {
                "time": {
                  "id": "time",
                  "type": "string"
                },
                "request": {
                  "id": "request",
                  "type": "object",
                  "properties": {
                    "name": "[object Object]",
                    "data": {
                      "id": "data",
                      "type": "object",
                      "properties": {
                        "when": {
                          "id": "when",
                          "type": "string"
                        },
                        "url": {
                          "id": "url",
                          "type": "string"
                        },
                        "name": "[object Object]"
                      },
                      "additionalProperties": true
                    },
                    "type": {
                      "id": "type",
                      "type": "string"
                    },
                    "priority": {
                      "id": "priority",
                      "type": "integer"
                    },
                    "nextRunAt": {
                      "id": "nextRunAt",
                      "type": "string"
                    },
                    "_id": {
                      "id": "_id",
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              },
              "additionalProperties": false,
              "required": [
                "time",
                "request"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "meta"
          ]
        }
      exampleItem: |
        {
          "meta": {
            "time": "2016-03-18T06:54:25.567Z",
            "request": {
              "name": "1 job",
              "data": {
                "when": "in 1 second",
                "url": "http://localhost:3000/testcburl",
                "name": "1 job"
              },
              "type": "normal",
              "priority": 0,
              "nextRunAt": "2016-03-18T06:54:26.568Z",
              "_id": "56eba62139a48fc980b3495d"
            }
          }
        }
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            example: |
              {}
              
schemas:
  - action-post-example: |
    {
      "meta": {
        "time": "2016-03-18T06:54:25.567Z",
        "request": {
          "name": "1 job",
          "data": {
            "when": "in 1 second",
            "url": "http://localhost:3000/testcburl",
            "name": "1 job"
          },
          "type": "normal",
          "priority": 0,
          "nextRunAt": "2016-03-18T06:54:26.568Z",
          "_id": "56eba62139a48fc980b3495d"
        }
      }
    }
 